#!/bin/bash

# .chdkptp install|uninstall
#    nota: el script siempre pregunta por un perfil de instalacion

# ./chdkptp install|uninstall profile=d|u || echo "fail"

function set_chdkptp_profile {

    if [[ "$1" =~ ^profile=[d|u]*$ ]]
     then
       profile="${1#*=}"
       echo "perfil de intalacion: '$profile'"
    else
      echo "Seleccione el perfil de instalación para CHDKPTP:"
      echo " - 'd' para versión dalclick"
      echo " - 'u' para última versión"
      echo " - 's' para salir"
      echo "(por defecto 'd')"
      read -p ">> " sel
      echo ""

      if [ "$sel" == "u" ]; then profile="u"
      elif [ "$sel" == "s" ]; then echo "Eligió salir."; exit 0
      else profile="d"
      fi
      PRINT_SELEC="Yes"
    fi

    if [ "$profile" == "u" ]
     then
      [[ "$PRINT_SELEC" == "Yes" ]] && \
        echo -e "Seleccionando version de CHDKPTP para 'última versión' (u)\n"
      CHDKPTP_VER=""
      IUP_VER="3.23"
      CD_VER="5.11.1"
      IM_VER="3.12"
    elif [ "$profile" == "d" ]
     then
      [[ "$PRINT_SELEC" == "Yes" ]] && \
        echo -e "Seleccionando version de CHDKPTP para 'dalclick' (d)\n"
      CHDKPTP_VER="461"
      IUP_VER="3.8"
      CD_VER="5.6.1"
      IM_VER="3.8.2"
    else
      echo "ERROR: profile = '$profile'"
      exit 1
    fi
}

function set_packages_param {
    DEPS="libusb-1.0-0 libusb-dev  libusb-1.0-0-dev libreadline-dev libreadline6-dev libcairo2-dev subversion git" # compatible ubuntu 18.04! #liblua5.1-0 lua5.1 liblua5.1-0-dev lua5.2 liblua5.2-dev
    # tecgraf deps "lua5.1 liblua5.1-0-dev lua5.2 liblua5.2-dev libfreetype6-dev" # libftgl-dev zlib1g-dev

    [[ "$PRINT_SELEC" == "Yes" ]] && {
        echo -e "Version a instalar:\n"
        echo "chdkptp: '$CHDKPTP_VER'"
        echo ""
        echo "Presione ENTER para continuar"
        echo "o CONTROL+C para cancelar"
        read -p ">> " continuar
    }
}

function install_chdkptp {
    echo "Verificando directorio para instalación"
    ./tools/check_src_dir $CHDKPTP_DIR && echo "OK" || {
        echo "error: no se pudo crear o modificar '$CHDKPTP_DIR'"
        exit 1
    }

    if ! ./tools/check_pkgs $DEPS; then
        if [ "root" != "$CURRENT_USER" ]; then
            echo "para instalar paquetes con apt-get es necesario hacerse root..."
            # todo check if deb-src enabled
            ./tools/run_as_root "apt-get install" "$DEPS" || {
                echo "error al instalar con apt-get"
                exit 1
            }
        else
            apt-get install $DEPS || {
                echo "error al instalar con apt-get"
                exit 1
            }
        fi
    fi
    check_tecgraf_ver || { echo "ERROR: dependencias insastifechas: librerías tecgraf. Ejecute '/opt/src/instaladores/tecgraf'"; exit 1; }
    svn co http://subversion.assembla.com/svn/chdkptp/trunk "$CHDKPTP_DIR"
    cd "$CHDKPTP_DIR"
    if [ "${CHDKPTP_VER}" != "" ]; then
      echo "revirtiendo a la versión '${CHDKPTP_VER}'..."
      svn up -r${CHDKPTP_VER} || exit 1
    fi
    config_file=`get_config_file`
    echo "$config_file" > config.mk
    make && return 0 || return 1
}

function get_config_file {
  IUP_LIB_DIR=`$TECGRAF_INSTALLER print_path=iup`
  CD_LIB_DIR=`$TECGRAF_INSTALLER print_path=cd`
  config_file_d="
IUP_SUPPORT=1
CD_SUPPORT=1
CD_USE_PLUS=cairo
PTPIP_SUPPORT=0

LUA_INCLUDE_DIR=/usr/include/lua5.1
LUA_LIB=lua5.1

DEBUG=1

IUP_LIB_DIR=${IUP_LIB_DIR}
IUP_INCLUDE_DIR=${IUP_LIB_DIR}/include
CD_LIB_DIR=${CD_LIB_DIR}
CD_INCLUDE_DIR=${CD_LIB_DIR}/include
"
#TODO!! chequera config_file_u!!
  config_file_u="
IUP_SUPPORT=1
CD_SUPPORT=1
CD_USE_PLUS=cairo
PTPIP_SUPPORT=0

LUA_INCLUDE_DIR=/usr/include/lua5.1
LUA_LIB=lua5.1

DEBUG=1

IUP_LIB_DIR=${IUP_LIB_DIR}
IUP_INCLUDE_DIR=${IUP_LIB_DIR}/include
CD_LIB_DIR=${CD_LIB_DIR}
CD_INCLUDE_DIR=${CD_LIB_DIR}/include
"
if [ "$profile" == 'u' ]
 then
  echo "$config_file_u"
  return 0
elif  [ "$profile" == 'd' ]
 then
  echo "$config_file_d"
  return 0
else
  return 1
fi
}

function test_chdkptp {
  cd "$CHDKPTP_DIR"
  [[ -f ./chdkptp ]] || return 1
  export LUA_PATH="./lua/?.lua"
  chdkptp_out=$( ./chdkptp -h | head -n 1 )
  if [ "$chdkptp_out" == "CHDK PTP control utility" ]; then
    echo "chdkptp instalado con éxito"
    return 0
  else
    echo "chdkptp no instalado"
    return 1
  fi
}

function check_tecgraf_ver { # tambien version!
  fail=''
  for lib in 'iup' 'cd' 'im'; do
    if ${TECGRAF_INSTALLER} "print_ver=${lib}" > /dev/null 2>&1
     then
      required_ver=$( eval echo "\$${lib^^}_VER" )
      installed_ver=`${TECGRAF_INSTALLER} "print_ver=${lib}"`
      echo -n "${lib}: instalada:'$installed_ver' requerida:'$required_ver' .."
      [[ "$installed_ver" == "$required_ver" ]] && {
        echo "OK"
      } || {
        echo "FAIL"
        fail="Yes"
      }
    else
      echo "ERROR: '$lib' no instalada."
      return 1
    fi
  done
  [[ "$fail" == "Yes" ]] && return 1 || return 0
}

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = #

[[ "`uname -o`" == "GNU/Linux" ]] || {
   echo "Este script solo puede utilizarse en sistemas 'GNU/Linux'"
   exit 1
}
#[[ "`uname -m`" == "x86_64" ]] && TYPE="_64" || TYPE=""

OWN_PATH="$PWD/$0"
CURRENT_USER="$USER"
TECGRAF_INSTALLER="$PWD/tecgraf" # TODO!!!
SRCDIR=/opt/src
CHDKPTP_DIR=$SRCDIR/chdkptp

case "$1" in
    uninstall)
    ;;
    '' | install)
        set_chdkptp_profile "$2" # $2=profile=d\u
        set_packages_param
        install_chdkptp || exit 1
        test_chdkptp && exit 0 || exit 1
    ;;
    test)
        test_chdkptp && exit 0 || exit 1
    ;;
    *)
        echo "ERROR: parametro desconocido '$1'"
        exit 1
esac

exit 0
