#!/bin/bash

# copia y descomprime los archivos tar de tecgraf

[[ "$1" == "" ]] && exit 1 || FILE="$1"
[[ "$2" == "" ]] && exit 1 || ORIG="$2"
[[ "$3" == "" ]] && exit 1 || FOLDER="$3"
[[ "$4" == "" ]] && UNTAR="$FOLDER" || UNTAR="$4"
cp -rp "$ORIG"/"$FILE" "$FOLDER"/
[[ -f "$FOLDER"/"$FILE" ]] || { 
   echo "no pudo copiarse '$FILE'"
   exit 1 
}
if [ -d "$FOLDER"/"$UNTAR" ]; then
  echo "'$FOLDER/$UNTAR' ya existe, archivos ya extraídos"
else
  mkdir "$FOLDER"/"$UNTAR" || exit 1
  tar xzvf "$FOLDER"/"$FILE" -C "$FOLDER"/"$UNTAR" || exit 1
fi
exit 0
