#!/bin/bash

# verifica que la carpeta exista y se pueda escribir
# si no puede y no es root, pide permisos y lo intenta como root

OWN_SCRIPT_DIR=$(dirname "$0")
cd "$OWN_SCRIPT_DIR"
OWN_DIR="$(pwd -P)"
OWN_PATH="$OWN_DIR/$0"


CURRENT_USER="$USER"

[[ "$1" == "" ]] && SRCDIR=/opt/src || SRCDIR="$1"

if [ "root" == "$CURRENT_USER" ]; then
   [[ -d "$SRCDIR" ]] || { 
      mkdir "$SRCDIR" || {
         if [[ -d "$(dirname "$SRCDIR")" ]]; then
            >&2 echo "error: no se pudo crear '$SRCDIR'"
         else
            >&2 echo "verifique que la carpeta padre exista"
         fi
         exit 1
      }   
   }
   chmod a+rw "$SRCDIR" && exit 0 || exit 1
else
   [[ -d "$SRCDIR" ]] || { 
      mkdir "$SRCDIR" || { 
         echo ""
         echo "para crear '$SRCDIR' es necesario hacerse root..."
         echo "(use control+c para cancelar)"
         "$OWN_DIR/run_as_root" "mkdir" "$SRCDIR" || { >&2 echo "No pudo crearse '$SRCDIR'"; exit 1;}
      }
   }
   if touch "$SRCDIR/writable_test" 2>/dev/null; then
      rm "$SRCDIR/writable_test"
      exit 0
   else
      echo ""
      echo "para cambiar los permisos en '$SRCDIR' es necesario hacerse root..."
      echo "(use control+c para cancelar)"
      "$OWN_DIR/run_as_root" "chmod" "a+rw" "$SRCDIR" || { 
      	>&2 echo "Error: no se pudieron modificar los permisos en '$SRCDIR'"
      	exit 1
      }
   fi
fi
