#!/bin/bash

[[ "$1" == "" ]] && exit 0

for pkg in "$@"
do
   if dpkg-query -W --showformat='${Status}\n' $pkg 2>/dev/null | grep -q "install ok installed"
     then
      echo "paquete '$pkg' OK"
   else
      echo "paquete '$pkg' No instalado"
      exit 1
   fi
done

exit 0