#!/bin/bash

# verifica que la carpeta exista y se pueda escribir
# si no puede y no es root, pide permisos y lo intenta como root

OWN_PATH="$PWD/$0"
CURRENT_USER="$USER"

[[ "$1" == "" ]] && SRCDIR=/opt/src || SRCDIR="$1"

if [ "root" == "$CURRENT_USER" ]; then
   [[ -d "$SRCDIR" ]] || { 
      mkdir "$SRCDIR" || {
         [[ -d "$(dirname "$SRCDIR")" ]] && \
            echo "error: no se pudo crear '$SRCDIR' porque no existe " ||\
            echo "verifique que la carpeta padre exista"
         exit 1
      }   
   }
   chmod a+rw "$SRCDIR" && exit 0 || exit 1
else
   [[ -d "$SRCDIR" ]] || { 
      mkdir "$SRCDIR" || { 
         echo ""
         echo "para crear '$SRCDIR' es necesario hacerse root..."
         echo "(use control+c para cancelar)"
         su root -c "$OWN_PATH $SRCDIR" || { echo "$OWN_PATH falló"; exit 1;}
      }
   }
   if touch "$SRCDIR/writable_test" 2>/dev/null; then
      rm "$SRCDIR/writable_test"
      exit 0
   else
      echo ""
      echo "para cambiar los permisos en '$SRCDIR' es necesario hacerse root..."
      echo "(use control+c para cancelar)"
      su root -c "$OWN_PATH $SRCDIR" || { echo "$OWN_PATH falló"; exit 1;}
      if touch "$SRCDIR/writable_test" 2>/dev/null; then
         rm "$SRCDIR/writable_test"
         exit 0
      else
         echo "error: root no pudo modificar '$SRCDIR'"
      fi
   fi
fi
